version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
              sudo apt install -yq jq
              sudo pip install -r requirements-dev.txt
              .circleci/pull-artifacts /tmp/compare $CIRCLE_REF_BUILD_NUM
              mkdir -p /tmp/artifacts
              pytest test.py --junit-xml=/tmp/artifacts/junit.xml --benchmark-json=/tmp/artifacts/bench.json --benchmark-compare=/tmp/compare/bench.json --benchmark-compare-fail=min:5%
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/artifacts
